#!/bin/sh

. "$(dirname "$0")"/prefix.sh

if test X"$1" = X
then
    die "Usage: $0 user_id"
fi

require_token
run_curl "$DOMAIN/authors/create" \
         -X POST  \
         -H "Content-Type: application/json" \
         -u "$TOKEN:" \
         --data-binary @- <<EOF
{
  "user_id": $1,
  "description": "The administrator of the service"
}
EOF
