#!/bin/sh

. "$(dirname "$0")"/prefix.sh

if test -z "${1+X}"
then
    die "Usage: $0 tag-name"
fi

require_token
run_curl "$DOMAIN/tags$Q" \
         -X POST  \
         -H "Content-Type: application/json" \
         -u "$TOKEN:" \
         --data-binary @- <<EOF
{
  "name": "$1"
}
EOF
