#!/bin/sh

. "$(dirname "$0")"/prefix.sh

if test -z "${1+X}"
then
    die "Usage: $0 category-name[.category-name]... [parent-category-id]"
fi

if test -z "$1"
then
    names_json_array="[]"
else
    names_json_array='["'$(echo "$1" | sed -e 's/\./", "/g')'"]'
fi

if test -n "$2"
then
    parent_fragment=', "parent_category_item_id": '$2
else
    parent_fragment=
fi

allow_token
run_curl "$DOMAIN/categories$Q" \
         -X POST  \
         -H "Content-Type: application/json" \
         --data-binary @- <<EOF
{
  "names": $names_json_array
  $parent_fragment
}
EOF
