#!/bin/sh

. "$(dirname "$0")"/prefix.sh

usage() {
    echo "Note: additional parameters are supported"
    echo "$0 [-category CATEGORY_ID] [-author AUTHOR_ID]"
}

if test $# -eq 0
then
    usage
fi

author_field=
category_field=

while test $# -gt 0
do
    arg=$1
    shift
    case "$arg" in
        -category)
            category_field="\"category_id\": $1,"
            shift ;;
        -author)
            author_field="\"author_id\": $1,"
            shift ;;
        *)
            echo "Unknown parameter $arg"
            usage
            die
    esac
done

allow_token
run_curl "$DOMAIN/drafts$Q" \
         -X POST  \
         -H "Content-Type: application/json" \
         --data-binary @- <<EOF
{
  "title": "GHC 19.0 has been released",
  "text": "See https://ghc.haskell.org",
  $author_field
  $category_field
  "photo": "http://localhost:3000/images/1",
  "photos": [
    {
        "base64_data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEX/TQBcNTh/AAAACklEQVR4nGNiAAAABgADNjd8qAAAAABJRU5ErkJggg==",
        "content_type": "image/png"
    }
  ],
  "tag_ids": [1]
}
EOF
