#!/bin/sh

. "$(dirname "$0")"/prefix.sh

case $# in
    1|2) user_id=$1; description=${2-EMPTY} ;;
    *) die "Usage: $0 user_id [author-description]" ;;
esac

allow_token
run_curl "$DOMAIN/authors$Q" \
         -X POST  \
         -H "Content-Type: application/json" \
         --data-binary @- <<EOF
{
  "user_id": $user_id,
  "description": "$description"
}
EOF
