#!/bin/sh

. "$(dirname "$0")"/prefix.sh

run_curl -X POST "$DOMAIN/users/create$1" -H "Content-Type: application/json" --data-binary @- <<'EOF'
{
  "first_name": "John",
  "last_name": "Doe",
  "avatar": {
    "base64_data": "qqqq",
    "content_type": "application/octet-stream"
  }
}
EOF
