#!/bin/sh

. "$(dirname "$0")"/prefix.sh

if test X"$1" = X
then
    die "Usage: $0 draft_id"
fi

draft_id=$1

require_token
run_curl "$DOMAIN/drafts/$draft_id" \
         -X POST  \
         -u "$TOKEN:"
